#!/usr/bin/bash
echo "Waiting up to 2 minutes to get collect reliable reference data ..."
echo
prevtemp=0
prevtime=0
counter=0

while sleep 1; do
#echo "XXXXX cycle:"$counter "prevtime "$prevtime "heattime "$heattime "heattemp "$heattemp " prevtemp "$prevtemp "heatrate"$heatrate

heatpair=$(tail -3 /var/log/syslog|grep heat_|awk '{print $3"   "$10}' | sed -e 's/:\([0-9]\)\([0-9]\)//2' -e 's/temp=//' -e 's/,//')
heattime=$(echo $heatpair|awk '{print $1}')
heattemp=$(echo $heatpair|awk '{print $2}')

if [[ "$prevtime" != "$heattime" ]]
   then
      if [[ "$counter" -gt 1 ]] # Skip first rounds due to mid-minute starts
         then
            heatdiff=`echo "scale=0; $heattemp-$prevtemp" | bc`
            heatrate=`echo "scale=0; $heatdiff*60" | bc`
            #echo "heattemp - prevtemp=: ("$heattemp "-" $prevtemp ") -> heatdiff = "$heatdiff "-> heatrate = "$heatrate
            echo "prevtime "$prevtime "heattime "$heattime "Temp "$heattemp " Heatrate "$heatrate
            prevtemp=$heattemp
         else
            counter=$((counter + 1))
         fi
	    prevtime=$heattime
      #echo "Counter="$counter
   fi
done

/*
this script outputs info below pulled fom the system log file like this.
I dont care if there are duplicate entries, I do 3 lines at a time because
 when the oven lags behind the keep-up value then other lines of
 info get dropped into the system log also.

17:07   1209.55
17:07   1209.55
17:07   1209.59
17:07   1209.59
17:07   1209.69
17:07   1209.71
17:07   1209.71
17:08   1209.76
17:08   1209.76
17:08   1209.77
17:08   1209.77
17:08   1209.83
17:08   1209.83
17:08   1209.93
17:08   1209.92
17:08   1209.92

If the time hasn't changed from the previous entry, delete the current entry.

The MOMENT the time changes at all, take a difference of the temperatures
between NOW and the saved value, then multiply this value times 60 to get
rate of heating change per hour.

Print this to the screen (or beter yet, return the output to the HTML screen)
*/
