#!/usr/bin/env python3
import warnings, os, sys

### CHEMATEX ###
### CHEMATEX ###
### CHEMATEX ###

#### Swap services
os.system("sudo systemctl start chematex.service &")
os.system("sudo systemctl stop rhode.service &")

#### Echo process to user
os.system ("sleep 2")
os.system("ps aux | grep 'pi\/rhode' | awk '{print $2"   "$12}'")
os.system("ps aux | grep 'pi\/chematex' | awk '{print $2"   "$12}'")
os.system("ps aux | grep 'pi\/jason-kiln-controller' | awk '{print $2"   "$12}'")

