#!/usr/bin/env python3
import time
### JASON ###
### JASON ###
### JASON ###

#### MARK TILLES START BLINKING GREEN LED WHEN SERVICE IS RUNNING
from gpiozero import Button, LEDBoard
from signal import pause
import warnings, os, sys
green_ledGPIO = 6
green_led=LEDBoard(green_ledGPIO)
green_led.blink(on_time=1, off_time=1)
#green_led.off
#### END - MARK TILLES START BLINKING GREEN LED WHEN SERVICE IS RUNNING

#### Swap services
os.system("sudo systemctl start jason-kiln-controller &")

#### Echo process to user
os.system ("sleep 2")
os.system("ps aux | grep 'pi\/rhode' | awk '{print $2"   "$12}'")
os.system("ps aux | grep 'pi\/chematex' | awk '{print $2"   "$12}'")
os.system("ps aux | grep 'pi\/jason-kiln-controller' | awk '{print $2"   "$12}'")

