#!/usr/bin/env python3

import warnings, os, sys
#### Echo process to user
os.system ("sleep 2")
os.system("ps aux | grep 'pi\/rhode' | awk '{print $2"   "$12}'")
os.system("ps aux | grep 'pi\/chematex' | awk '{print $2"   "$12}'")
os.system("ps aux | grep 'pi\/jason-kiln-controller' | awk '{print $2"   "$12}'")

